console.time('Your code took');
console.log('hello console');
console.log(4+30);
console.log(40);
console.log(true);
console.log([34,4,5,6]);
  console.table({sonu: 'this', monu:46});
console.warn('this is warning');
// console.clear();
console.timeEnd('Your code took');
// console.assert(566<189, 'age > 189 is not possible');
console.error('This is an error');